import { PREDEFINE_UNIT_NAME, PREDEFINE_ADMINISTRATIVELEVEL_NAME, PREDEFINE_FEATURETYPE_NAME, PREDEFINE_EVENTINDICATOR_NAME, PREDEFINE_EVENTTOPIC_NAME, PREDEFINE_EVENTLEVEL_NAME, PREDEFINE_EVENTSEVERITY_NAME, PREDEFINE_EVENTCERTAINTY_NAME, PREDEFINE_EVENTSTATUS_NAME, PREDEFINE_EVENTURGENCY_NAME, PREDEFINE_EVENTRESPONSE_NAME, PREDEFINE_PARTYGROUP_NAME, PREDEFINE_PARTYROLE_NAME, PREDEFINE_EVENTGROUP_NAME, PREDEFINE_EVENTTYPE_NAME, PREDEFINE_EVENTFUNCTION_NAME, PREDEFINE_EVENTACTION_NAME, PREDEFINE_EVENTQUESTION_NAME, PREDEFINE_ADMINISTRATIVEAREA_NAME, PREDEFINE_NAMESPACE_UNIT, PREDEFINE_NAMESPACE_PARTYROLE, PREDEFINE_NAMESPACE_NOTIFICATIONTEMPLATE, EVENT_RELATIONS } from '@codetanzania/ewea-internals';
export * from '@codetanzania/ewea-internals';
import { sortedUniq, mergeObjects } from '@lykmapipo/common';
import { getString } from '@lykmapipo/env';
export * from '@lykmapipo/constants';
export { applyTransformsOn, connect, csvPathFor, dataPathFor, findAdministrativeAreaChildren, findAdministrativeAreaParents, findAdministrativeLevelChildren, findAdministrativeLevelParents, findChangelogDefaults, findDefaultPredefines, findEventDefaults, findPartyDefaults, geoJsonPathFor, jsonPathFor, pathFor, preloadChangelogRelated, preloadEventRelated, preloadPartyRelated, preloadRelated, processCsvSeed, readCsvFile, seed, seedAdministrativeAreas, seedAdministrativeLevels, seedAgencies, seedEvent, seedEventActionCatalogues, seedEventActions, seedEventCertainties, seedEventFunctions, seedEventGroups, seedEventIndicators, seedEventLevels, seedEventQuestions, seedEventResponses, seedEventSeverities, seedEventStatuses, seedEventTopics, seedEventTypes, seedEventUrgencies, seedEvents, seedFeatureTypes, seedFeatures, seedFocals, seedFromCsv, seedFromJson, seedFromSeeds, seedNotificationTemplates, seedParty, seedPartyGroups, seedPartyRoles, seedPathFor, seedPermissions, seedPredefine, seedUnits, shapeFilePathFor, syncIndexes, transformGeoFields, transformOtherFields, transformSeedKeys, transformToEventSeed, transformToPartySeed, transformToPredefineSeed } from '@lykmapipo/constants';
import 'async';
import '@lykmapipo/mongoose-common';
import '@lykmapipo/file';
import 'path';
import 'lodash';
import '@lykmapipo/logger';
import '@lykmapipo/geo-tools';
import '@lykmapipo/predefine';
import '@lykmapipo/permission';
import 'mongoose-locale-schema';

const DEFAULT_UNIT_NAME = getString(
  'DEFAULT_UNIT_NAME',
  PREDEFINE_UNIT_NAME
);

const DEFAULT_ADMINISTRATIVELEVEL_NAME = getString(
  'DEFAULT_ADMINISTRATIVELEVEL_NAME',
  PREDEFINE_ADMINISTRATIVELEVEL_NAME
);

const DEFAULT_FEATURETYPE_NAME = getString(
  'DEFAULT_FEATURETYPE_NAME',
  PREDEFINE_FEATURETYPE_NAME
);

const DEFAULT_EVENTINDICATOR_NAME = getString(
  'DEFAULT_EVENTINDICATOR_NAME',
  PREDEFINE_EVENTINDICATOR_NAME
);

const DEFAULT_EVENTTOPIC_NAME = getString(
  'DEFAULT_EVENTTOPIC_NAME',
  PREDEFINE_EVENTTOPIC_NAME
);

const DEFAULT_EVENTLEVEL_NAME = getString(
  'DEFAULT_EVENTLEVEL_NAME',
  PREDEFINE_EVENTLEVEL_NAME
);

const DEFAULT_EVENTSEVERITY_NAME = getString(
  'DEFAULT_EVENTSEVERITY_NAME',
  PREDEFINE_EVENTSEVERITY_NAME
);

const DEFAULT_EVENTCERTAINTY_NAME = getString(
  'DEFAULT_EVENTCERTAINTY_NAME',
  PREDEFINE_EVENTCERTAINTY_NAME
);

const DEFAULT_EVENTSTATUS_NAME = getString(
  'DEFAULT_EVENTSTATUS_NAME',
  PREDEFINE_EVENTSTATUS_NAME
);

const DEFAULT_EVENTURGENCY_NAME = getString(
  'DEFAULT_EVENTURGENCY_NAME',
  PREDEFINE_EVENTURGENCY_NAME
);

const DEFAULT_EVENTRESPONSE_NAME = getString(
  'DEFAULT_EVENTRESPONSE_NAME',
  PREDEFINE_EVENTRESPONSE_NAME
);

const DEFAULT_PARTYGROUP_NAME = getString(
  'DEFAULT_PARTYGROUP_NAME',
  PREDEFINE_PARTYGROUP_NAME
);

const DEFAULT_PARTYROLE_NAME = getString(
  'DEFAULT_PARTYROLE_NAME',
  PREDEFINE_PARTYROLE_NAME
);

const DEFAULT_EVENTGROUP_NAME = getString(
  'DEFAULT_EVENTGROUP_NAME',
  PREDEFINE_EVENTGROUP_NAME
);

const DEFAULT_EVENTTYPE_NAME = getString(
  'DEFAULT_EVENTTYPE_NAME',
  PREDEFINE_EVENTTYPE_NAME
);

const DEFAULT_EVENTFUNCTION_NAME = getString(
  'DEFAULT_EVENTFUNCTION_NAME',
  PREDEFINE_EVENTFUNCTION_NAME
);

const DEFAULT_EVENTACTION_NAME = getString(
  'DEFAULT_EVENTACTION_NAME',
  PREDEFINE_EVENTACTION_NAME
);

const DEFAULT_EVENTQUESTION_NAME = getString(
  'DEFAULT_EVENTQUESTION_NAME',
  PREDEFINE_EVENTQUESTION_NAME
);

const DEFAULT_ADMINISTRATIVEAREA_NAME = getString(
  'DEFAULT_ADMINISTRATIVEAREA_NAME',
  PREDEFINE_ADMINISTRATIVEAREA_NAME
);

const DEFAULT_EVENT_NUMBER = getString(
  'DEFAULT_EVENT_NUMBER',
  undefined
);

const DEFAULT_NAMES = sortedUniq([
  DEFAULT_UNIT_NAME,
  DEFAULT_ADMINISTRATIVELEVEL_NAME,
  DEFAULT_FEATURETYPE_NAME,
  DEFAULT_EVENTINDICATOR_NAME,
  DEFAULT_EVENTTOPIC_NAME,
  DEFAULT_EVENTLEVEL_NAME,
  DEFAULT_EVENTSEVERITY_NAME,
  DEFAULT_EVENTCERTAINTY_NAME,
  DEFAULT_EVENTSTATUS_NAME,
  DEFAULT_EVENTURGENCY_NAME,
  DEFAULT_EVENTRESPONSE_NAME,
  DEFAULT_PARTYGROUP_NAME,
  DEFAULT_PARTYROLE_NAME,
  DEFAULT_EVENTGROUP_NAME,
  DEFAULT_EVENTTYPE_NAME,
  DEFAULT_EVENTFUNCTION_NAME,
  DEFAULT_EVENTACTION_NAME,
  DEFAULT_EVENTQUESTION_NAME,
  DEFAULT_ADMINISTRATIVEAREA_NAME,
]);

const DEFAULT_PATHS = mergeObjects(
  {
    unit: { namespace: PREDEFINE_NAMESPACE_UNIT },
    role: { namespace: PREDEFINE_NAMESPACE_PARTYROLE },
    template: { namespace: PREDEFINE_NAMESPACE_NOTIFICATIONTEMPLATE },
  },
  EVENT_RELATIONS
);

export { DEFAULT_ADMINISTRATIVEAREA_NAME, DEFAULT_ADMINISTRATIVELEVEL_NAME, DEFAULT_EVENTACTION_NAME, DEFAULT_EVENTCERTAINTY_NAME, DEFAULT_EVENTFUNCTION_NAME, DEFAULT_EVENTGROUP_NAME, DEFAULT_EVENTINDICATOR_NAME, DEFAULT_EVENTLEVEL_NAME, DEFAULT_EVENTQUESTION_NAME, DEFAULT_EVENTRESPONSE_NAME, DEFAULT_EVENTSEVERITY_NAME, DEFAULT_EVENTSTATUS_NAME, DEFAULT_EVENTTOPIC_NAME, DEFAULT_EVENTTYPE_NAME, DEFAULT_EVENTURGENCY_NAME, DEFAULT_EVENT_NUMBER, DEFAULT_FEATURETYPE_NAME, DEFAULT_NAMES, DEFAULT_PARTYGROUP_NAME, DEFAULT_PARTYROLE_NAME, DEFAULT_PATHS, DEFAULT_UNIT_NAME };
