import {
  PREDEFINE_UNIT_NAME,
  PREDEFINE_ADMINISTRATIVELEVEL_NAME,
  PREDEFINE_FEATURETYPE_NAME,
  PREDEFINE_EVENTINDICATOR_NAME,
  PREDEFINE_EVENTTOPIC_NAME,
  PREDEFINE_EVENTLEVEL_NAME,
  PREDEFINE_EVENTSEVERITY_NAME,
  PREDEFINE_EVENTCERTAINTY_NAME,
  PREDEFINE_EVENTSTATUS_NAME,
  PREDEFINE_EVENTURGENCY_NAME,
  PREDEFINE_EVENTRESPONSE_NAME,
  PREDEFINE_PARTYGROUP_NAME,
  PREDEFINE_PARTYROLE_NAME,
  PREDEFINE_EVENTGROUP_NAME,
  PREDEFINE_EVENTTYPE_NAME,
  PREDEFINE_EVENTFUNCTION_NAME,
  PREDEFINE_EVENTACTION_NAME,
  PREDEFINE_EVENTQUESTION_NAME,
  PREDEFINE_ADMINISTRATIVEAREA_NAME,
  PREDEFINE_NAMESPACE_UNIT,
  PREDEFINE_NAMESPACE_PARTYROLE,
  PREDEFINE_NAMESPACE_FEATURETYPE,
  PREDEFINE_NAMESPACE_EVENTINDICATOR,
  PREDEFINE_NAMESPACE_EVENTTOPIC,
  PREDEFINE_NAMESPACE_VEHICLE,
  PREDEFINE_NAMESPACE_EVENTFUNCTION,
  PREDEFINE_NAMESPACE_EVENTACTION,
  PREDEFINE_NAMESPACE_EVENTQUESTION,
  PREDEFINE_NAMESPACE_FEATURE,
  PREDEFINE_NAMESPACE_EVENTACTIONCATALOGUE,
  PREDEFINE_NAMESPACE_NOTIFICATIONTEMPLATE,
  EVENT_RELATIONS,
  PREDEFINE_DEFAULTS,
} from '@codetanzania/ewea-internals';
import { mapValues, omit } from 'lodash';
import { sortedUniq, mergeObjects } from '@lykmapipo/common';
import { getNumber, getString } from '@lykmapipo/env';
import {
  localizedValuesFor,
  localizedAbbreviationsFor,
} from 'mongoose-locale-schema';

export const DEFAULT_PREDEFINE_NAME = getString(
  'DEFAULT_PREDEFINE_NAME',
  'Unknown'
);
export const DEFAULT_PREDEFINE_COLOR = getString(
  'DEFAULT_PREDEFINE_COLOR',
  '#6D9EEB'
);
export const DEFAULT_PREDEFINE_WEIGHT = getNumber(
  'DEFAULT_PREDEFINE_WEIGHT',
  1000
);

export const DEFAULT_PREDEFINE_RELATION = {
  _id: null,
  strings: {
    name: localizedValuesFor({ en: DEFAULT_PREDEFINE_NAME }),
    abbreviation: localizedAbbreviationsFor({ en: DEFAULT_PREDEFINE_NAME }),
    color: DEFAULT_PREDEFINE_COLOR,
  },
  numbers: { weight: DEFAULT_PREDEFINE_WEIGHT },
};

export const DEFAULT_UNIT_NAME = getString(
  'DEFAULT_UNIT_NAME',
  PREDEFINE_UNIT_NAME
);

export const DEFAULT_ADMINISTRATIVELEVEL_NAME = getString(
  'DEFAULT_ADMINISTRATIVELEVEL_NAME',
  PREDEFINE_ADMINISTRATIVELEVEL_NAME
);

export const DEFAULT_FEATURETYPE_NAME = getString(
  'DEFAULT_FEATURETYPE_NAME',
  PREDEFINE_FEATURETYPE_NAME
);

export const DEFAULT_EVENTINDICATOR_NAME = getString(
  'DEFAULT_EVENTINDICATOR_NAME',
  PREDEFINE_EVENTINDICATOR_NAME
);

export const DEFAULT_EVENTTOPIC_NAME = getString(
  'DEFAULT_EVENTTOPIC_NAME',
  PREDEFINE_EVENTTOPIC_NAME
);

export const DEFAULT_EVENTLEVEL_NAME = getString(
  'DEFAULT_EVENTLEVEL_NAME',
  PREDEFINE_EVENTLEVEL_NAME
);

export const DEFAULT_EVENTSEVERITY_NAME = getString(
  'DEFAULT_EVENTSEVERITY_NAME',
  PREDEFINE_EVENTSEVERITY_NAME
);

export const DEFAULT_EVENTCERTAINTY_NAME = getString(
  'DEFAULT_EVENTCERTAINTY_NAME',
  PREDEFINE_EVENTCERTAINTY_NAME
);

export const DEFAULT_EVENTSTATUS_NAME = getString(
  'DEFAULT_EVENTSTATUS_NAME',
  PREDEFINE_EVENTSTATUS_NAME
);

export const DEFAULT_EVENTURGENCY_NAME = getString(
  'DEFAULT_EVENTURGENCY_NAME',
  PREDEFINE_EVENTURGENCY_NAME
);

export const DEFAULT_EVENTRESPONSE_NAME = getString(
  'DEFAULT_EVENTRESPONSE_NAME',
  PREDEFINE_EVENTRESPONSE_NAME
);

export const DEFAULT_PARTYGROUP_NAME = getString(
  'DEFAULT_PARTYGROUP_NAME',
  PREDEFINE_PARTYGROUP_NAME
);

export const DEFAULT_PARTYROLE_NAME = getString(
  'DEFAULT_PARTYROLE_NAME',
  PREDEFINE_PARTYROLE_NAME
);

export const DEFAULT_EVENTGROUP_NAME = getString(
  'DEFAULT_EVENTGROUP_NAME',
  PREDEFINE_EVENTGROUP_NAME
);

export const DEFAULT_EVENTTYPE_NAME = getString(
  'DEFAULT_EVENTTYPE_NAME',
  PREDEFINE_EVENTTYPE_NAME
);

export const DEFAULT_EVENTFUNCTION_NAME = getString(
  'DEFAULT_EVENTFUNCTION_NAME',
  PREDEFINE_EVENTFUNCTION_NAME
);

export const DEFAULT_EVENTACTION_NAME = getString(
  'DEFAULT_EVENTACTION_NAME',
  PREDEFINE_EVENTACTION_NAME
);

export const DEFAULT_EVENTQUESTION_NAME = getString(
  'DEFAULT_EVENTQUESTION_NAME',
  PREDEFINE_EVENTQUESTION_NAME
);

export const DEFAULT_ADMINISTRATIVEAREA_NAME = getString(
  'DEFAULT_ADMINISTRATIVEAREA_NAME',
  PREDEFINE_ADMINISTRATIVEAREA_NAME
);

export const DEFAULT_EVENT_NUMBER = getString(
  'DEFAULT_EVENT_NUMBER',
  undefined
);

export const DEFAULT_NAMES = sortedUniq([
  DEFAULT_UNIT_NAME,
  DEFAULT_ADMINISTRATIVELEVEL_NAME,
  DEFAULT_FEATURETYPE_NAME,
  DEFAULT_EVENTINDICATOR_NAME,
  DEFAULT_EVENTTOPIC_NAME,
  DEFAULT_EVENTLEVEL_NAME,
  DEFAULT_EVENTSEVERITY_NAME,
  DEFAULT_EVENTCERTAINTY_NAME,
  DEFAULT_EVENTSTATUS_NAME,
  DEFAULT_EVENTURGENCY_NAME,
  DEFAULT_EVENTRESPONSE_NAME,
  DEFAULT_PARTYGROUP_NAME,
  DEFAULT_PARTYROLE_NAME,
  DEFAULT_EVENTGROUP_NAME,
  DEFAULT_EVENTTYPE_NAME,
  DEFAULT_EVENTFUNCTION_NAME,
  DEFAULT_EVENTACTION_NAME,
  DEFAULT_EVENTQUESTION_NAME,
  DEFAULT_ADMINISTRATIVEAREA_NAME,
]);

export const DEFAULT_PATHS = mergeObjects(
  {
    unit: { namespace: PREDEFINE_NAMESPACE_UNIT },
    role: { namespace: PREDEFINE_NAMESPACE_PARTYROLE },
    template: { namespace: PREDEFINE_NAMESPACE_NOTIFICATIONTEMPLATE },
  },
  EVENT_RELATIONS
);

export const DEFAULT_SEEDS_IGNORE = [
  PREDEFINE_NAMESPACE_FEATURETYPE,
  PREDEFINE_NAMESPACE_EVENTINDICATOR,
  PREDEFINE_NAMESPACE_EVENTTOPIC,
  PREDEFINE_NAMESPACE_VEHICLE,
  PREDEFINE_NAMESPACE_EVENTFUNCTION,
  PREDEFINE_NAMESPACE_EVENTACTION,
  PREDEFINE_NAMESPACE_EVENTQUESTION,
  PREDEFINE_NAMESPACE_FEATURE,
  PREDEFINE_NAMESPACE_EVENTACTIONCATALOGUE,
  PREDEFINE_NAMESPACE_NOTIFICATIONTEMPLATE,
];

export const DEFAULT_SEEDS = mapValues(
  omit(PREDEFINE_DEFAULTS, ...DEFAULT_SEEDS_IGNORE),
  (defaultValue, namespace) => {
    return {
      // _id: null, TODO: genarate default object ids
      namespace,
      strings: {
        name: localizedValuesFor({ en: defaultValue }),
        abbreviation: localizedAbbreviationsFor({ en: defaultValue }),
        color: DEFAULT_PREDEFINE_COLOR,
      },
      numbers: { weight: DEFAULT_PREDEFINE_WEIGHT },
      booleans: { default: true, system: true },
    };
  }
);
