import {
  PREDEFINE_UNIT_NAME,
  PREDEFINE_ADMINISTRATIVELEVEL_NAME,
  PREDEFINE_FEATURETYPE_NAME,
  PREDEFINE_EVENTINDICATOR_NAME,
  PREDEFINE_EVENTTOPIC_NAME,
  PREDEFINE_EVENTLEVEL_NAME,
  PREDEFINE_EVENTSEVERITY_NAME,
  PREDEFINE_EVENTCERTAINTY_NAME,
  PREDEFINE_EVENTSTATUS_NAME,
  PREDEFINE_EVENTURGENCY_NAME,
  PREDEFINE_EVENTRESPONSE_NAME,
  PREDEFINE_PARTYGROUP_NAME,
  PREDEFINE_PARTYROLE_NAME,
  PREDEFINE_EVENTGROUP_NAME,
  PREDEFINE_EVENTTYPE_NAME,
  PREDEFINE_EVENTFUNCTION_NAME,
  PREDEFINE_EVENTACTION_NAME,
  PREDEFINE_EVENTQUESTION_NAME,
  PREDEFINE_ADMINISTRATIVEAREA_NAME,
} from '@codetanzania/ewea-internals';
import { getString } from '@lykmapipo/env';

export const DEFAULT_UNIT_NAME = getString(
  'DEFAULT_UNIT_NAME',
  PREDEFINE_UNIT_NAME
);

export const DEFAULT_ADMINISTRATIVELEVEL_NAME = getString(
  'DEFAULT_ADMINISTRATIVELEVEL_NAME',
  PREDEFINE_ADMINISTRATIVELEVEL_NAME
);

export const DEFAULT_FEATURETYPE_NAME = getString(
  'DEFAULT_FEATURETYPE_NAME',
  PREDEFINE_FEATURETYPE_NAME
);

export const DEFAULT_EVENTINDICATOR_NAME = getString(
  'DEFAULT_EVENTINDICATOR_NAME',
  PREDEFINE_EVENTINDICATOR_NAME
);

export const DEFAULT_EVENTTOPIC_NAME = getString(
  'DEFAULT_EVENTTOPIC_NAME',
  PREDEFINE_EVENTTOPIC_NAME
);

export const DEFAULT_EVENTLEVEL_NAME = getString(
  'DEFAULT_EVENTLEVEL_NAME',
  PREDEFINE_EVENTLEVEL_NAME
);

export const DEFAULT_EVENTSEVERITY_NAME = getString(
  'DEFAULT_EVENTSEVERITY_NAME',
  PREDEFINE_EVENTSEVERITY_NAME
);

export const DEFAULT_EVENTCERTAINTY_NAME = getString(
  'DEFAULT_EVENTCERTAINTY_NAME',
  PREDEFINE_EVENTCERTAINTY_NAME
);

export const DEFAULT_EVENTSTATUS_NAME = getString(
  'DEFAULT_EVENTSTATUS_NAME',
  PREDEFINE_EVENTSTATUS_NAME
);

export const DEFAULT_EVENTURGENCY_NAME = getString(
  'DEFAULT_EVENTURGENCY_NAME',
  PREDEFINE_EVENTURGENCY_NAME
);

export const DEFAULT_EVENTRESPONSE_NAME = getString(
  'DEFAULT_EVENTRESPONSE_NAME',
  PREDEFINE_EVENTRESPONSE_NAME
);

export const DEFAULT_PARTYGROUP_NAME = getString(
  'DEFAULT_PARTYGROUP_NAME',
  PREDEFINE_PARTYGROUP_NAME
);

export const DEFAULT_PARTYROLE_NAME = getString(
  'DEFAULT_PARTYROLE_NAME',
  PREDEFINE_PARTYROLE_NAME
);

export const DEFAULT_EVENTGROUP_NAME = getString(
  'DEFAULT_EVENTGROUP_NAME',
  PREDEFINE_EVENTGROUP_NAME
);

export const DEFAULT_EVENTTYPE_NAME = getString(
  'DEFAULT_EVENTTYPE_NAME',
  PREDEFINE_EVENTTYPE_NAME
);

export const DEFAULT_EVENTFUNCTION_NAME = getString(
  'DEFAULT_EVENTFUNCTION_NAME',
  PREDEFINE_EVENTFUNCTION_NAME
);

export const DEFAULT_EVENTACTION_NAME = getString(
  'DEFAULT_EVENTACTION_NAME',
  PREDEFINE_EVENTACTION_NAME
);

export const DEFAULT_EVENTQUESTION_NAME = getString(
  'DEFAULT_EVENTQUESTION_NAME',
  PREDEFINE_EVENTQUESTION_NAME
);

export const DEFAULT_ADMINISTRATIVEAREA_NAME = getString(
  'DEFAULT_ADMINISTRATIVEAREA_NAME',
  PREDEFINE_ADMINISTRATIVEAREA_NAME
);

export const DEFAULT_EVENT_NUMBER = getString(
  'DEFAULT_EVENT_NUMBER',
  undefined
);
